### ISSUE TITLE
[ERROR] .ipa files not implemented yet.

### ISSUE THREAD

**Issue by im23pds** [vincentcox/StaCoAn#53]
[INFO] Decompiling app...
[ERROR] .ipa files not implemented yet. 

im used window

**Comment by vincentcox** [comment]
It's correct that IPA files are not implemented yet.

I broke my head multiple times thinking on a cross-platform solution to decompile IPA files. Unfortunately, all 64bit apps (which are the big majority of the applications) are encrypted and must be decrypted in runtime (on a running jailbroken device). 

It is possible to just unzip the IPA file and go trough the resources, but 90% of the findings will not be found because the actual code can't be scanned.

If someone from the community knows a cross-platform way to face this issue, please let me know!

I will add the tag "help wanted" so we can keep this issue open.

**Comment by im23pds** [comment]
oh thanks
